<?php

function decrypt($item) {
		if ($item == "Air")						{$item = "0";}
		elseif ($item == "stone")					{$item = "1";}
		elseif ($item == "grass")					{$item = "2";}
		elseif ($item == "dirt")					{$item = "3";}
		elseif ($item == "cobble")					{$item = "4";}
		elseif ($item == "wood")					{$item = "5";}
		elseif ($item == "sapling")				{$item = "6";}
		elseif ($item == "adminium")				{$item = "7";}
		elseif ($item == "water")					{$item = "8";}
		elseif ($item == "stillwater")				{$item = "9";}
		elseif ($item == "lava")					{$item = "10";}
		elseif ($item == "slava")					{$item = "11";}
		elseif ($item == "sand")					{$item = "12";}
		elseif ($item == "gravel")					{$item = "13";}
		elseif ($item == "goldore")				{$item = "14";}
		elseif ($item == "ironore")				{$item = "15";}
		elseif ($item == "coalore")				{$item = "16";}
		elseif ($item == "log")					{$item = "17";}
		elseif ($item == "leaves")					{$item = "18";}
		elseif ($item == "sponge")					{$item = "19";}
		elseif ($item == "glass")					{$item = "20";}
		elseif ($item == "lapislazuliore")			{$item = "21";}
		elseif ($item == "lazuliblock")				{$item = "22";}
		elseif ($item == "dispenser")				{$item = "23";}
		elseif ($item == "sandstone")				{$item = "24";}
		elseif ($item == "musicblock")				{$item = "25";}
		elseif ($item == "bedblock")				{$item = "26";}
		elseif ($item == "Wool")					{$item = "35";}
		elseif ($item == "flower")					{$item = "37";}
		elseif ($item == "rose")					{$item = "38";}
		elseif ($item == "brownmushroom")			{$item = "39";}
		elseif ($item == "redmushroom")				{$item = "40";}
		elseif ($item == "gold")					{$item = "41";}
		elseif ($item == "goldblock")					{$item = "41";}
		elseif ($item == "iron")					{$item = "42";}
		elseif ($item == "ironblock")					{$item = "42";}
		elseif ($item == "doublestair")				{$item = "43";}
		elseif ($item == "brickwall")				{$item = "45";}
		elseif ($item == "tnt")					{$item = "46";}
		elseif ($item == "bookshelf")				{$item = "47";}
		elseif ($item == "mossycobblestone")			{$item = "48";}
		elseif ($item == "obsidian")				{$item = "49";}
		elseif ($item == "torch")					{$item = "50";}
		elseif ($item == "mobspawner")				{$item = "52";}
		elseif ($item == "woodstairs")				{$item = "53";}
		elseif ($item == "stair")					{$item = "53";}
		elseif ($item == "chest")					{$item = "54";}
		elseif ($item == "redstonewire")			{$item = "55";}
		elseif ($item == "diamondore")				{$item = "56";}
		elseif ($item == "diamond")				{$item = "57";}
		elseif ($item == "diamondblock")			{$item = "57";}
		elseif ($item == "workbench")				{$item = "58";}
		elseif ($item == "crops")					{$item = "59";}
		elseif ($item == "soil")					{$item = "60";}
		elseif ($item == "furnace")				{$item = "61";}
		elseif ($item == "litfurnace")				{$item = "62";}
		elseif ($item == "signblock")				{$item = "63";}
		elseif ($item == "wooddoorblock")			{$item = "64";}
		elseif ($item == "ladder")					{$item = "65";}
		elseif ($item == "rails")					{$item = "66";}
		elseif ($item == "stairs")					{$item = "67";}
		elseif ($item == "signblocktop")			{$item = "68";}
		elseif ($item == "lever")					{$item = "69";}
		elseif ($item == "stoneplate")				{$item = "70";}
		elseif ($item == "irondoorblock")			{$item = "71";}
		elseif ($item == "woodplate")				{$item = "72";}
		elseif ($item == "redstoneore")				{$item = "73";}
		elseif ($item == "redstoneorealt")			{$item = "74";}
		elseif ($item == "redstonetorchoff")			{$item = "75";}
		elseif ($item == "redstonetorchon")			{$item = "76";}
		elseif ($item == "button")					{$item = "77";}
		elseif ($item == "snow")					{$item = "78";}
		elseif ($item == "ice")					{$item = "79";}
		elseif ($item == "snowblock")				{$item = "80";}
		elseif ($item == "cactus")					{$item = "81";}
		elseif ($item == "clayblock")				{$item = "82";}
		elseif ($item == "reedblock")				{$item = "83";}
		elseif ($item == "jukebox")				{$item = "84";}
		elseif ($item == "fence")					{$item = "85";}
		elseif ($item == "pumpkin")				{$item = "86";}
		elseif ($item == "netherstone")				{$item = "87";}
		elseif ($item == "slowsand")				{$item = "88";}
		elseif ($item == "lightstone")				{$item = "89";}
		elseif ($item == "portal")					{$item = "90";}
		elseif ($item == "jacko")					{$item = "91";}
		elseif ($item == "cakeblock")				{$item = "92";}
		elseif ($item == "repeateroff")				{$item = "93";}
		elseif ($item == "repeateron")				{$item = "94";}
		elseif ($item == "ironshovel")             	{$item = "256";}
		elseif ($item == "ironspade")            		{$item = "256";}
		elseif ($item == "ironpickaxe")             	{$item = "257";}
		elseif ($item == "ironpick")             		{$item = "257";}
		elseif ($item == "ironaxe")             		{$item = "258";}
		elseif ($item == "flintandsteel")          	{$item = "259";}
		elseif ($item == "lighter")             		{$item = "259";}
		elseif ($item == "apple")             		{$item = "260";}
		elseif ($item == "bow")             			{$item = "261";}
		elseif ($item == "arrow")             		{$item = "262";}
		elseif ($item == "coal")             			{$item = "263";}
		elseif ($item == "diamond")            	 	{$item = "264";}
		elseif ($item == "ironbar")             		{$item = "265";}
		elseif ($item == "goldbar")             		{$item = "266";}
		elseif ($item == "ironsword")             		{$item = "267";}
		elseif ($item == "woodsword")             		{$item = "268";}
		elseif ($item == "woodshovel")             	{$item = "269";}
		elseif ($item == "woodspade")             		{$item = "269";}
		elseif ($item == "woodpickaxe")           	  	{$item = "270";}
		elseif ($item == "woodpick")             		{$item = "270";}
		elseif ($item == "woodaxe")             		{$item = "271";}
		elseif ($item == "stonesword")             	{$item = "272";}
		elseif ($item == "stoneshovel")            	{$item = "273";}
		elseif ($item == "stonespade")             	{$item = "273";}
		elseif ($item == "stonepickaxe")           	{$item = "274";}
		elseif ($item == "stonepick")             		{$item = "274";}
		elseif ($item == "stoneaxe")             		{$item = "275";}
		elseif ($item == "diamondsword")          		{$item = "276";}
		elseif ($item == "diamondshovel")         	  	{$item = "277";}
		elseif ($item == "diamondspade")            	{$item = "277";}
		elseif ($item == "diamondpickaxe")         	{$item = "278";}
		elseif ($item == "diamondpick")            	{$item = "278";}
		elseif ($item == "diamondaxe")             	{$item = "279";}
		elseif ($item == "stick")             		{$item = "280";}
		elseif ($item == "bowl")             			{$item = "281";}
		elseif ($item == "bowlwithsoup")            	{$item = "282";}
		elseif ($item == "soupbowl")             		{$item = "282";}
		elseif ($item == "soup")             			{$item = "282";}
		elseif ($item == "goldsword")             		{$item = "283";}
		elseif ($item == "goldshovel")             	{$item = "284";}
		elseif ($item == "goldspade")             		{$item = "284";}
		elseif ($item == "goldpickaxe")            	{$item = "285";}
		elseif ($item == "goldpick")             		{$item = "285";}
		elseif ($item == "goldaxe")            		{$item = "286";}
		elseif ($item == "string")             		{$item = "287";}
		elseif ($item == "feather")             		{$item = "288";}
		elseif ($item == "gunpowder")             		{$item = "289";}
		elseif ($item == "woodhoe")            		{$item = "290";}
		elseif ($item == "stonehoe")             		{$item = "291";}
		elseif ($item == "ironhoe")             		{$item = "292";}
		elseif ($item == "diamondhoe")             	{$item = "293";}
		elseif ($item == "goldhoe")             		{$item = "294";}
		elseif ($item == "seeds")             		{$item = "295";}
		elseif ($item == "wheat")             		{$item = "296";}
		elseif ($item == "bread")             		{$item = "297";}
		elseif ($item == "leatherhelmet")           {$item = "298";}
		elseif ($item == "leatherchestplate")       {$item = "299";}
		elseif ($item == "leatherpants")            {$item = "300";}
		elseif ($item == "leatherboots")            {$item = "301";}
		elseif ($item == "chainmailhelmet")         {$item = "302";}
		elseif ($item == "chainmailchestplate")     {$item = "303";}
		elseif ($item == "chainmailpants")          {$item = "304";}
		elseif ($item == "chainmailboots")          {$item = "305";}
		elseif ($item == "ironhelmet")              {$item = "306";}
		elseif ($item == "ironchestplate")          {$item = "307";}
		elseif ($item == "ironpants")               {$item = "308";}
		elseif ($item == "ironboots")             	{$item = "309";}
		elseif ($item == "diamondhelmet")           {$item = "310";}
		elseif ($item == "diamondchestplate")       {$item = "311";}
		elseif ($item == "diamondpants")            {$item = "312";}
		elseif ($item == "diamondboots")            {$item = "313";}
		elseif ($item == "goldhelmet")             	{$item = "314";}
		elseif ($item == "goldchestplate")          {$item = "315";}
		elseif ($item == "goldpants")             	{$item = "316";}
		elseif ($item == "goldboots")             	{$item = "317";}
		elseif ($item == "flint")             		{$item = "318";}
		elseif ($item == "meat")             		{$item = "319";}
		elseif ($item == "pork")             		{$item = "319";}
		elseif ($item == "cookedmeat")             	{$item = "320";}
		elseif ($item == "cookedpork")             	{$item = "320";}
		elseif ($item == "painting")             	{$item = "321";}
		elseif ($item == "paintings")             	{$item = "321";}
		elseif ($item == "goldenapple")             {$item = "322";}
		elseif ($item == "sign")             		{$item = "323";}
		elseif ($item == "wooddoor")             	{$item = "324";}
		elseif ($item == "bucket")             		{$item = "325";}
		elseif ($item == "waterbucket")             {$item = "326";}
		elseif ($item == "lavabucket")             	{$item = "327";}
		elseif ($item == "minecart")             	{$item = "328";}
		elseif ($item == "saddle")             		{$item = "329";}
		elseif ($item == "irondoor")             	{$item = "330";}
		elseif ($item == "redstonedust")            {$item = "331";}
		elseif ($item == "snowball")             	{$item = "332";}
		elseif ($item == "boat")             		{$item = "333";}
		elseif ($item == "leather")             	{$item = "334";}
		elseif ($item == "milkbucket")             	{$item = "335";}
		elseif ($item == "brick")             		{$item = "336";}
		elseif ($item == "clay")             		{$item = "337";}
		elseif ($item == "reed")             		{$item = "338";}
		elseif ($item == "paper")            		{$item = "339";}
		elseif ($item == "book")             		{$item = "340";}
		elseif ($item == "slimeorb")             	{$item = "341";}
		elseif ($item == "storageminecart")         {$item = "342";}
		elseif ($item == "poweredminecart")         {$item = "343";}
		elseif ($item == "egg")             		{$item = "344";}
		elseif ($item == "compass")             	{$item = "345";}
		elseif ($item == "fishingrod")             	{$item = "346";}
		elseif ($item == "watch")             		{$item = "347";}
		elseif ($item == "lightstonedust")          {$item = "348";}
		elseif ($item == "lightdust")             	{$item = "348";}
		elseif ($item == "rawfish")             	{$item = "349";}
		elseif ($item == "fish")             		{$item = "349";}
		elseif ($item == "cookedfish")             	{$item = "350";}
		elseif ($item == "inksac")             		{$item = "351";}
		elseif ($item == "bone")             		{$item = "352";}
		elseif ($item == "sugar")             		{$item = "353";}
		elseif ($item == "cake")             		{$item = "354";}
		elseif ($item == "bed")             		{$item = "355";}
		elseif ($item == "repeater")             	{$item = "356";}
		elseif ($item == "EnderPearl")             	{$item = "368";}
		elseif ($item == "goldrecord")             	{$item = "2256";}
		elseif ($item == "greenrecord")             {$item = "2257";}

		// Begin of Enemy decryption
		elseif ($item == "Chicken")					{$item = "m1";}
		elseif ($item == "Cow")						{$item = "m2";}
		elseif ($item == "Creeper")					{$item = "m3";}
		elseif ($item == "Ghast")						{$item = "m4";}
		elseif ($item == "Pig")						{$item = "m5";}
		elseif ($item == "PigZombie")					{$item = "m6";}
		elseif ($item == "Sheep")						{$item = "m7";}
		elseif ($item == "Skeleton")					{$item = "m8";}
		elseif ($item == "Spider")						{$item = "m9";}
		elseif ($item == "Zombie")						{$item = "m10";}
		elseif ($item == "Wolf")						{$item = "m11";}
		elseif ($item == "Slime")						{$item = "m12";}
		elseif ($item == "Squid")						{$item = "m13";}
		elseif ($item == "Player")						{$item = "m14";}
		elseif ($item == "player")						{$item = "m14";}
		elseif ($item == "Enderman")					{$item = "m15";}
		elseif ($item == "CaveSpider")					{$item = "m16";}
		elseif ($item == "Spiderjockey")				{$item = "m17";}
		elseif ($item == "Giant")						{$item = "m18";}
		elseif ($item == "Monster")					{$item = "m19";}
		elseif ($item == "Blaze")						{$item = "m20";}
		elseif ($item == "LivingEntity")				{$item = "m21";}
		elseif ($item == "EnderDragon")					{$item = "m22";}
		elseif ($item == "MagmaCube")					{$item = "m23";}
		elseif ($item == "Silverfish")					{$item = "m24";}
		elseif ($item == "Snowman")					{$item = "m25";}
		elseif ($item == "Villager")					{$item = "m26";}
		elseif ($item == "MushroomCow")					{$item = "m27";}

		// Begin of Damage decryption
		elseif ($item == "total")						{$item = "d0";}
		elseif ($item == "drowning")					{$item = "d1";}
		elseif ($item == "suffocation")					{$item = "d2";}
		elseif ($item == "fall")						{$item = "d3";}
		elseif ($item == "unknown")					{$item = "d4";}
		elseif ($item == "explosion")					{$item = "d5";}
		elseif ($item == "firetick")					{$item = "d6";}
		elseif ($item == "unknown")					{$item = "d7";}
		elseif ($item == "CACTUS")						{$item = "81";}
		elseif ($item == "Arrow")						{$item = "262";}
		elseif ($item == "(null)")						{$item = "d4";}
		elseif ($item == "fire")						{$item = "10";}
		elseif ($item == "Fireball")					{$item = "10";}
		elseif ($item == "Fish")						{$item = "349";}
		elseif ($item == "Entity")						{$item = "m18";}
		elseif ($item == "entityattack")				{$item = "m18";}
		elseif ($item == "Snowball")					{$item = "332";}
		elseif ($item == "TNTPrimed")					{$item = "46";}
		elseif ($item == "Egg")						{$item = "344";}
		
		else {$item = "$item";}
		return $item;
}